### ISSUE TITLE
(Jetbrains Rider) Unable to cast object of type RectangleViewModel to type INode

### ISSUE THREAD

**Issue by AGhostik** [wieslawsoltes/NodeEditor#59]
How to reproduce:
1. Download/clone repo
2. Open NodeEditor.sln with Jetbrains Rider (with Visual Studio not reproducible)
3. Run Debug NodeEditor.Desktop 

I can't figure out what the difference is between Rider and VS. I am currently in the process of researching the issue.

System.InvalidCastException: Unable to cast object of type 'NodeEditorDemo.ViewModels.Nodes.RectangleViewModel' to type 'NodeEditor.Model.INode'.
   at CompiledAvaloniaXaml.XamlIlHelpers.NodeEditor.Model.INode,NodeEditorAvalonia.Model.Content!Getter(Object)
   at Avalonia.Data.Core.ClrPropertyInfo.Get(Object target) in /_/src/Avalonia.Base/Data/Core/ClrPropertyInfo.cs:line 27
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.get_Value() in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs:line 88
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.SendCurrentValue() in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs:line 132

**Comment by wieslawsoltes** [comment]
Try 11.1
